// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsa7cnc_J6cR5g-FdRpg6xO6Zzx3-ogfA',
    appId: '1:1091780394304:web:5d1dd3e6ed6a4814060ea5',
    messagingSenderId: '1091780394304',
    projectId: 'hanas-talk',
    authDomain: 'hanas-talk.firebaseapp.com',
    storageBucket: 'hanas-talk.firebasestorage.app',
    measurementId: 'G-E30T7XRPFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFiptgQzsHHFt9dC8Q_Q0x7zJlAu_OyMI',
    appId: '1:1091780394304:android:fde0fd51e508e810060ea5',
    messagingSenderId: '1091780394304',
    projectId: 'hanas-talk',
    storageBucket: 'hanas-talk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9DOI-mRpED-BuY9mhNH5_5O5rUChm2X0',
    appId: '1:1091780394304:ios:5b8708fcbe3e985d060ea5',
    messagingSenderId: '1091780394304',
    projectId: 'hanas-talk',
    storageBucket: 'hanas-talk.firebasestorage.app',
    iosBundleId: 'com.example.hanas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9DOI-mRpED-BuY9mhNH5_5O5rUChm2X0',
    appId: '1:1091780394304:ios:5b8708fcbe3e985d060ea5',
    messagingSenderId: '1091780394304',
    projectId: 'hanas-talk',
    storageBucket: 'hanas-talk.firebasestorage.app',
    iosBundleId: 'com.example.hanas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsa7cnc_J6cR5g-FdRpg6xO6Zzx3-ogfA',
    appId: '1:1091780394304:web:7efae363e5fb9e53060ea5',
    messagingSenderId: '1091780394304',
    projectId: 'hanas-talk',
    authDomain: 'hanas-talk.firebaseapp.com',
    storageBucket: 'hanas-talk.firebasestorage.app',
    measurementId: 'G-19WTE2XL60',
  );
}
